### PR TITLE
Fix ICC for internal IPv6 networks

### LINKED ISSUE #23: No ICC for IPv6 nework if "--internal" is used
## Problem/Bug

Running a fresh Docker CE system without the default bridge and only a custo network created with the following command:
```
sudo docker network create --ipv6 --subnet 172.22.99.0/24 --subnet fdef:0:0:99::/64 --internal my99
```

iptables (IPv4) FORWARD (and referenced) chains:
```
Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  br-d403f56263c1 br-d403f56263c1  0.0.0.0/0            0.0.0.0/0

Chain DOCKER (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      br-d403f56263c1 !172.30.99.0/24       0.0.0.0/0           
    0     0 DROP       all  --  br-d403f56263c1 *       0.0.0.0/0           !172.30.99.0/24      
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0    
```

ip6tables (IPv6) FORWARD (and referenced) chains:
```
Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-ISOLATION  all      *      *       ::/0                 ::/0

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      br-d403f56263c1 !fddd:0:0:99::/64     ::/0                
    0     0 DROP       all      br-d403f56263c1 *       ::/0                !fddd:0:0:99::/64    
    0     0 RETURN     all      *      *       ::/0                 ::/0
```

***As you can see, ip6tables is missing a rule to allow traffic between containers on such an "--internal" network.***

## Solution/Fix

We need to change this part of `manager.go`:
```go
	if network.internal {
		return &Ruleset{
			NewPrependRule(TableFilter, ChainDockerIsolation,
				"!", "-s", network.subnet.String(),
				"-o", network.bridge,
				"-j", "DROP"),
			NewPrependRule(TableFilter, ChainDockerIsolation,
				"!", "-d", network.subnet.String(),
				"-i", network.bridge,
				"-j", "DROP"),
		}
	}

	iccAction := "ACCEPT"
	if !network.icc {
		iccAction = "DROP"
	}
```

We have to check for icc flag before creating the ruleset for an internal network.

If you would set icc to false for this internal network, FORWARD will contain the following rule:
```
    0     0 DROP     all  --  br-d403f56263c1 br-d403f56263c1  0.0.0.0/0            0.0.0.0/0
```
So we only need to move the icc check before the internal ruleset generation and always create a rule, wich will use iccAction as its action.

### PR DESCRIPTION
**Pull request by bephinix**
Fixes #23

### CODE REVIEW

**Comment by bephinix** [comment]
@robbertkl Should I use `NewRule` or `NewPrependRule`?

**Comment by robbertkl** [comment]
> @robbertkl Should I use `NewRule` or `NewPrependRule`?

It depends on where the rule should be in relation to others.

**Comment by bephinix** [comment]
@robbertkl Changed it, IPv4 implementation uses PREPEND. Should be fine now.

**Comment by bephinix** [comment]
Sorry, need to recheck this PREPEND/APPEND point.

**Comment by bephinix** [comment]
Ok, we need to insert this rule after the docker isolation chain so I changed it to `NewRule`.
@robbertkl What do you think? :question:

**Comment by bephinix** [comment]
@robbertkl Any news?

**Comment by robbertkl** [comment]
I'm sorry, I did not have time yet to take a look at this and test it properly. Do you have this running for a while without issues?

Do I need a specific Docker version for this? This is not related to the new DOCKER-USER stuff recently added to Docker, right?

**Comment by bephinix** [comment]
@robbertkl 

I am currently running it on four servers (Dual Stack Mode) without any problems. IPv6 ICC works perfectly fine (as IPv4 ICC).

No, it is not connected to `DOCKER-USER`. It basically implements the `--internal` flag for IPv6 networks corrrectly. AFAIK Docker adds this feature for IPv4 a while ago, so this fix should work with all Docker versions which has the feature for IPv4 built in.

**Comment by robbertkl** [comment]
Thanks man, I've just merged it. I will update some other stuff and bake a new release.

**Comment by robbertkl** [comment]
Pushed a new release as well ([v0.3.3](https://github.com/robbertkl/docker-ipv6nat/releases/tag/v0.3.3)), Docker images are available on Docker Hub.

**Pull request merged**
