### PR TITLE
Log ruleset changes to stdout

### LINKED ISSUE #31: Feature Request: Log ip6tables rules beeing added or removed to stdout
This tool works great! 
For debugging purposes, it would be nice if actions like rule changes would be logged to `stdout`.

### PR DESCRIPTION
**Pull request by bephinix**
### New Feature

If one calls `docker-ipv6nat` with the `-debug` flag, every added or removed rule will be logged to stdout.

---
Fixes #31

### CODE REVIEW

**Comment by robbertkl** [comment]
I think some changes are missing. This only adds the flag, but no logging yet for added/removed rules.

**Comment by bephinix** [comment]
@robbertkl Yes, I only created the PR. Missing parts will be pushed soon. :smile:

**Comment by robbertkl** [comment]
OK, just add a comment when it's ready to be merged.

**Comment by bephinix** [comment]
@robbertkl Wait, I will add some docs for it.

**Comment by bephinix** [comment]
@robbertkl Now it is ready for review.

**Pull request merged**
