### PR TITLE
Updated: Dockerfile & gh-actions

### PR DESCRIPTION
**Pull request by GoliathLabs**
Hi, I added a dependabot configuration that checks for updates of the dockerfile, github actions and Go modules used on a monthly basis. I also added some labels to the dockerfile and a github action that adds a linter for Go and a git leak test.

### CODE REVIEW

**Comment by robbertkl** [comment]
Hi @GoliathLabs, those seem like great improvements! Few notes:

* This project still uses [manul](https://github.com/kovetskiy/manul) where dependencies are inlined as git submodules. Wouldn't that conflict?
* For the `APP_VERSION` arg, I think the `push.sh` script will need changes as well; that's what I use to do the cross platform builds (using `buildx`)

**Comment by GoliathLabs** [comment]
Yeah, you're right. I've removed the dependabot check for the go modules.

I've added GitHub Actions which automatically build and push a new image to the ghcr.io registry. We might change that to docker hub for this package though. You may want to have a look at it :)

**Comment by robbertkl** [comment]
Don't think I'm ready to delete `push.sh`, as I'd still want the images on Docker Hub for now.

Also, it seems the `docker` workflow only tags as `:latest`? What I currently do is only do releases for tagged commits, at which point a new image is published with both the `:latest` and `:vX` tags. Intermediate (untagged) commits to master don't become images.

**Comment by GoliathLabs** [comment]
Okay, I'll have a look at it then :)

**Comment by GoliathLabs** [comment]
Hi, I have added the push.sh script with the label changes again. The GitHub action now pushes to ghcr.io with the tag testing.

**Comment by GoliathLabs** [comment]
@robbertkl Any news regarding this?

**Comment by GoliathLabs** [comment]
I've added the gitsubmodule ecosystem to the dependabot config. Now updates for the git submodules should also arrive here 😄

**Pull request closed without merging**
